spring:
  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: false

  output:
    ansi:
      enabled: NEVER

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

  endpoint:
    health:
      show-details: never

  prometheus:
    metrics:
      export:
        enabled: true