spring:

  application:
    name: couplead

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: widget-cache-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.example.couplead.event.dto
        spring.json.value.default.type: com.example.couplead.event.dto.CoupleAnniversaryUpdatedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      #  객체를 JSON으로 직렬화
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  elasticsearch:
    uris: ${ELASTICSEARCH_URI}

  output:
    ansi:
      enabled: ALWAYS

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

logging:

  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace