### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"12345678",
    "nickname":"park"
}

### 로그인
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

@accessToken= {{login.response.body.data.accessToken}}
@refreshToken= {{login.response.body.data.refreshToken}}

### 정보 조회
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}

### 토큰 재발급
POST http://localhost:8080/api/auth/reissue
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 초대 코드 생성
# @name invite
POST http://localhost:8080/api/couples/invite
Authorization: Bearer {{accessToken}}

@inviteCode= {{invite.response.body.data.inviteCode}}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

########################################################################
### B
########################################################################

### 회원가입 B
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "email":"testB@test.com",
    "password":"87654321",
    "nickname":"kim"
}

### 로그인 B
# @name loginB
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "testB@test.com",
  "password": "87654321"
}

@accessTokenB= {{loginB.response.body.data.accessToken}}
@refreshTokenB= {{loginB.response.body.data.refreshToken}}

### 초대 코드 생성 B
POST http://localhost:8080/api/couples/invite
Authorization: Bearer {{accessTokenB}}

########################################################################

### 연결
POST http://localhost:8080/api/couples/connect
Authorization: Bearer {{accessTokenB}}
Content-Type: application/json

{
  "inviteCode": "{{inviteCode}}"
}

### 커플 조회
GET http://localhost:8080/api/couples/me
Authorization: Bearer {{accessToken}}

### 기념일 수정
PATCH http://localhost:8080/api/couples/anniversary
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "anniversary": "2026-08-04"
}

### 커플 위젯 조회
GET http://localhost:8080/api/widgets/couple
Authorization: Bearer {{accessToken}}

########################################################################

### Chat 조회
GET http://localhost:8080/api/chat/1
Authorization: Bearer {{accessToken}}