### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"12345678",
    "nickname":"park"
}

### 로그인
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

@accessToken= {{login.response.body.data.accessToken}}
@refreshToken= {{login.response.body.data.refreshToken}}

### 웹 로그인
# @name login
POST http://localhost:8080/api/auth/web/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}


### 정보 조회
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}

### 토큰 재발급
POST http://localhost:8080/api/auth/reissue
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 초대 코드 생성
# @name invite
POST http://localhost:8080/api/couples/invite
Authorization: Bearer {{accessToken}}

@inviteCode= {{invite.response.body.data.inviteCode}}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

########################################################################
### B
########################################################################

### 회원가입 B
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "email":"testB@test.com",
    "password":"87654321",
    "nickname":"kim"
}

### 로그인 B
# @name loginB
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "testB@test.com",
  "password": "87654321"
}

@accessTokenB= {{loginB.response.body.data.accessToken}}
@refreshTokenB= {{loginB.response.body.data.refreshToken}}

### 초대 코드 생성 B
POST http://localhost:8080/api/couples/invite
Authorization: Bearer {{accessTokenB}}

########################################################################

### 연결
POST http://localhost:8080/api/couples/connect
Authorization: Bearer {{accessTokenB}}
Content-Type: application/json

{
  "inviteCode": "{{inviteCode}}"
}

### 커플 조회
GET http://localhost:8080/api/couples/me
Authorization: Bearer {{accessToken}}

########################################################################

### 기념일 생성
POST http://localhost:8080/api/anniversaries
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "두번째 테스트",
  "type": "BIRTHDAY",
  "repeatType": "YEARLY",
  "anniversaryDate": "2023-08-05"
}

### 기념일 조회
GET http://localhost:8080/api/anniversaries
Authorization: Bearer {{accessToken}}

### 기념일 수정
PATCH http://localhost:8080/api/widgets/anniversary
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "anniversaryId": 2
}

### 커플 위젯 조회
GET http://localhost:8080/api/widgets/couple
Authorization: Bearer {{accessToken}}

########################################################################

### Chat 조회
GET http://localhost:8080/api/chat/1
Authorization: Bearer {{accessToken}}

########################################################################

### 접속 조회
GET http://localhost:8080/api/presence/1
Authorization: Bearer {{accessToken}}

########################################################################

### 내 위치 수정
PATCH http://localhost:8080/api/users/me/location
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "country": "KR",
  "city": "Seoul",
  "timezone": "Asia/Seoul",
  "latitude": 37.5665,
  "longitude": 126.9780
}

### B 위치 수정
PATCH http://localhost:8080/api/users/me/location
Authorization: Bearer {{accessTokenB}}
Content-Type: application/json

{
  "country": "US",
  "city": "Arizona",
  "timezone": "America/Phoenix",
  "latitude": 33.4484,
  "longitude": -112.0740
}

########################################################################

### Read API 호출
POST http://localhost:8080/api/chat/1/read
Authorization: Bearer {{accessToken}}

########################################################################

### 채팅 페이지네이션 최근 10개
# @name chat
GET http://localhost:8080/api/chat/1?size=10
Authorization: Bearer {{accessToken}}

@nextCursor = {{chat.response.body.data.nextCursor}}

### 채팅 페이지네이션 이전 10개
# @name chat
GET http://localhost:8080/api/chat/1?beforeMessageId={{nextCursor}}&size=10
Authorization: Bearer {{accessToken}}

@nextCursor = {{chat.response.body.data.nextCursor}}

########################################################################

### 닉네임 변경
PATCH http://localhost:8080/api/users/me/profile
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nickname": "Lee"
}

####################################################

### Elasticsearch 테스트 재색인 API
POST http://localhost:8080/api/chat/search/reindex
Authorization: Bearer {{accessToken}}

### Elasticsearch 테스트 API
GET http://localhost:8080/api/chat/1/search?keyword=채팅&useNori=true
Authorization: Bearer {{accessToken}}

### Elasticsearch 테스트 API
GET http://localhost:8080/api/chat/1/search?keyword=채팅&useNori=false
Authorization: Bearer {{accessToken}}

### Elasticsearch 테스트 API
GET http://localhost:8080/api/chat/1/search?keyword=먹
Authorization: Bearer {{accessToken}}